#!/bin/bash

TMUX_PLUGIN_PATH=${HOME}/.tmux/plugins
TMUX_RESURRECT_PATH=${HOME}/.tmux/resurrect

if [ ! -f ${TMUX_PLUGIN_PATH}/tpm/scripts/install_plugins.sh ]; then
    echo "Installing Tmux Plugin Manager..."
    mkdir -p ${TMUX_PLUGIN_PATH}
    git clone https://github.com/tmux-plugins/tpm ${TMUX_PLUGIN_PATH}/tpm
    tmux source-file ~/.tmux.conf
    ${TMUX_PLUGIN_PATH}/tpm/scripts/install_plugins.sh
    
    ## tmux-resurrect
    mkdir -p ${TMUX_RESURRECT_PATH}
    tmux source-file ~/.tmux.conf
fi
