#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)

function makelink () {
    rm -rf ${2}/${1}
    ln -fs ${SCRIPT_DIR}/${1} ${2}/
}

function addline() {
    linestr=$1
    tgtfile=$2

    strcnt=`cat "${tgtfile}" 2>/dev/null | grep "${linestr}" | wc -l`

    if [ 0 -eq ${strcnt} ]
    then
        echo "${linestr}" >> "${tgtfile}"
    fi
}

## XDG
mkdir -p ${HOME}/.config
mkdir -p ${HOME}/.local/share
mkdir -p ${HOME}/.cache
mkdir -p ${HOME}/.local/state

## dotfiles
for dotfile in .emacs.d .gitignore  .hgrc .screenrc  .vimrc
do
    makelink ${dotfile} ${HOME}
done

## helper scripts
local_bin=${HOME}/.local/bin
mkdir -p ${local_bin}

for binfile in tmux-pane-border
do
    makelink ${binfile} ${local_bin}
    chmod +x ${local_bin}/${binfile}
done

## bashrc
addline ". \"${SCRIPT_DIR}/.bashrc\"" ~/.bashrc

## zshrc
echo 'ZDOTDIR=$HOME/.config/zsh' > ~/.zshenv
mkdir -p $HOME/.config/zsh
ln -fs ${SCRIPT_DIR}/.zshrc ${HOME}/.config/zsh/.zshrc

## tmux
TMUX_ROOT=${HOME}/.config/tmux
mkdir -p ${TMUX_ROOT}
ln -fs ${SCRIPT_DIR}/.tmux.conf ${TMUX_ROOT}/tmux.conf
for tmuxconf in ${SCRIPT_DIR}/tmux/*.conf
do
    ln -fs ${tmuxconf} ${TMUX_ROOT}
done
touch ${TMUX_ROOT}/device.conf

## Install plugins
source ${SCRIPT_DIR}/install_vim_plugins
source ${SCRIPT_DIR}/install_tmux_plugins
source ${SCRIPT_DIR}/install_zsh_plugins

## NeoVim
NEOVIM_ROOT=${HOME}/.config/nvim
mkdir -p ${NEOVIM_ROOT}/lua
ln -fs ${SCRIPT_DIR}/nvim/init.lua ${NEOVIM_ROOT}/init.lua
for vimlua in ${SCRIPT_DIR}/nvim/lua/*.lua
do
    ln -fs ${vimlua} ${NEOVIM_ROOT}/lua
done
touch ${NEOVIM_ROOT}/lua/device.lua

## Golang
mkdir -p ${HOME}/.local/goroot
mkdir -p ${HOME}/.local/go
