#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0); pwd)

function makelink () {
    rm -rf ${2}/${1}
    ln -s ${SCRIPT_DIR}/${1} ${2}/
}

function addline() {
    linestr=$1
    tgtfile=$2

    strcnt=`cat "${tgtfile}" 2>/dev/null | grep "${linestr}" | wc -l`

    if [ 0 -eq ${strcnt} ]
    then
        echo "${linestr}" >> "${tgtfile}"
    fi
}

## dotfiles
for dotfile in .emacs.d .gitignore  .hgrc  .tmux.conf .screenrc  .vimrc  .zshrc
do
    makelink ${dotfile} ${HOME}
done

## helper scripts
local_bin=${HOME}/.local/bin
mkdir -p ${local_bin}

for binfile in tmux-pane-border
do
    makelink ${binfile} ${local_bin}
    chmod +x ${local_bin}/${binfile}
done

## bashrc
addline ". \"${SCRIPT_DIR}/.bashrc\"" ~/.bashrc

## Install plugins
source ${SCRIPT_DIR}/install_vim_plugins
source ${SCRIPT_DIR}/install_tmux_plugins