#!/bin/bash

function makelink () {
    cwd=`dirname "${0}"`
    expr "${0}" : "/.*" > /dev/null || cwd=`(cd "${cwd}" && pwd)`
    rm -rf ${HOME}/${1}
    ln -s ${cwd}/${1} ${HOME}/
}


for dotfile in .emacs.d .gitconfig .gitignore  .hgrc  .screenrc  .vimrc  .zshrc
do
    makelink ${dotfile}
done

myself_path=`readlink -f "${0}"`
cwd=`dirname "${myself_path}"`
echo ". ${cwd}/.bashrc" >> ~/.bashrc
