(when (require 'package nil t)
  (add-to-list 'package-archives '
               ("gnu" . "http://elpa.gnu.org/packages/"))
  (add-to-list 'package-archives '
               ("melpa" . "http://melpa.milkbox.net/packages/") t)
  (add-to-list 'package-archives '
               ("marmalade" . "http://marmalade-repo.org/packages/"))
  (setq package-user-dir "~/local/lib/emacs/package/")
  (package-initialize)

  (defvar installing-package-list
    '(
      ctable
      deferred
      epc
      flymake
      imenu+
      ipython
      jedi
      popup
      python-environment
      python-pep8
      scala-mode2
      5x5
      ada-mode
      add-log
      align
      allout
      allout-widgets
      ange-ftp
      animate
      ansi-color
      antlr-mode
      arc-mode
      array
      artist
      asm-mode
      autoarg
      autoconf
      autoinsert
      autorevert
      avl-tree
      avoid
      battery
      benchmark
      bib-mode
      bibtex
      bibtex-style
      bindat
      binhex
      blackbox
      bookmark
      browse-url
      bs
      bubbles
      bug-reference
      calc
      calculator
      calendar
      cap-words
      cc-guess
      cc-mode
      cdl
      cedet
      cfengine
      check-declare
      checkdoc
      chistory
      cl
      cl-lib
      cmacexp
      cmuscheme
      color
      compare-w
      completion
      conf-mode
      cookie1
      copyright
      cperl-mode
      crisp
      crm
      css-mode
      cua-base
      cvs-status
      cwarn
      dabbrev
      dbus
      dcl-mode
      decipher
      delim-col
      delphi
      delsel
      descr-text
      desktop
      dframe
      diary-lib
      diff
      diff-mode
      dig
      dirtrack
      disass
      dissociate
      dns
      dns-mode
      doc-view
      doctor
      double
      dunnet
      ebnf2ps
      ebrowse
      ebuff-menu
      echistory
      ede
      edebug
      ediff
      edmacro
      edt
      ehelp
      eieio
      eldoc
      electric
      elide-head
      elint
      elp
      emacs-lock
      emerge
      enriched
      epa
      epg
      erc
      ert
      ert-x
      eshell
      etags
      eudc
      ewoc
      executable
      expand
      ezimage
      f90
      face-remap
      feedmail
      ffap
      filecache
      filesets
      find-cmd
      find-dired
      find-file
      find-func
      find-gc
      find-lisp
      finder
      flow-ctrl
      flymake
      flyspell
      foldout
      follow
      footnote
      format-spec
      forms
      fortran
      fortune
      gamegrid
      gametree
      gdb-mi
      glasses
      gnus
      gnutls
      gomoku
      google-c-style
      goto-addr
      gs
      gud
      gulp
      handwrite
      hanoi
      hashcash
      help-at-pt
      hex-util
      hexl
      highlight-indentation
      hi-lock
      hideif
      hideshow
      hilit-chg
      hippie-exp
      hl-line
      hmac-def
      hmac-md5
      htmlfontify
      ibuffer
      icalendar
      icomplete
      icon
      idlwave
      ido
      ielm
      iimage
      image-dired
      image-file
      imap
      imenu
      inf-lisp
      info
      info-look
      info-xref
      informat
      inversion
      isearchb
      ispell
      iswitchb
      jka-compr
      js
      json
      kermit
      keypad
      kmacro
      landmark
      ld-script
      ldap
      life
      linum
      lisp-mnt
      loadhist
      locate
      log-edit
      log-view
      longlines
      lpr
      m4-mode
      macroexp
      mail-utils
      mailabbrev
      mailalias
      mailclient
      mairix
      make-mode
      makeinfo
      makesum
      man
      mantemp
      master
      mb-depth
      md4
      meese
      meta-mode
      metamail
      mh-e
      midnight
      minibuf-eldef
      misearch
      mixal-mode
      mode-local
      modula2
      morse
      mouse-copy
      mouse-drag
      mpc
      mpuz
      msb
      mspools
      net-utils
      netrc
      network-stream
      newsticker
      notifications
      novice
      nroff-mode
      ntlm
      nxml
      octave-mod
      org
      outline
      package
      page-ext
      paren
      parse-time
      pascal
      password-cache
      pcase
      pcomplete
      pcvs
      perl-mode
      picture
      po
      pong
      pp
      printing
      proced
      profiler
      prolog
      ps-mode
      ps-print
      pulse
      quickurl
      rcirc
      rcompile
      re-builder
      recentf
      refbib
      refer
      refill
      reftex
      reftex-auc
      reftex-cite
      reftex-dcr
      reftex-global
      reftex-index
      reftex-parse
      reftex-ref
      reftex-sel
      reftex-toc
      reftex-vars
      regexp-opt
      regi
      remember
      repeat
      reporter
      reposition
      reveal
      rfc2368
      rfc822
      ring
      rlogin
      rmail
      rot13
      rst
      ruby-mode
      ruler-mode
      rx
      sasl
      savehist
      saveplace
      sb-image
      scheme
      scroll-all
      scroll-lock
      secrets
      select
      semantic
      sendmail
      server
      ses
      sgml-mode
      sh-script
      shadow
      shadowfile
      shell
      simula
      skeleton
      smerge-mode
      smie
      smtpmail
      snake
      snmp-mode
      soap-client
      socks
      solitaire
      sort
      soundex
      speedbar
      spook
      sql
      srecode
      strokes
      studly
      subword
      supercite
      syntax
      t-mouse
      table
      tabulated-list
      talk
      tar-mode
      tcl
      telnet
      tempo
      term
      terminal
      testcover
      tex-mode
      texinfmt
      texinfo
      texnfo-upd
      thingatpt
      thumbs
      tildify
      time
      time-date
      time-stamp
      timeclock
      timezone
      tls
      tmm
      todo-mode
      tpu-edt
      tq
      trace
      tramp
      tree-widget
      two-column
      type-break
      uce
      underline
      undigest
      unrmail
      unsafep
      url
      uudecode
      vc
      vcursor
      vera-mode
      verilog-mode
      vhdl-mode
      vi
      view
      vip
      viper
      vt-control
      vt100-led
      w32-common-fns
      warnings
      wdired
      webjump
      which-func
      whitespace
      windmove
      winner
      woman
      ws-mode
      xesam
      xml
      xscheme
      xt-mouse
      yow
      zeroconf
      zone
      ))

  (defun install-using-packages ()
    (let ((not-installed (loop for x in installing-package-list
                               when (not (package-installed-p x))
                               collect x)))

      (when not-installed
        (package-refresh-contents)
        (dolist (pkg-no-installed)
          (package-install pkg))))
    )
    )
